// Copyright 2026 ptrvsrg.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	store "github.com/ptrvsrg/csi-driver-ipfs/pkg/driver/store"
	mock "github.com/stretchr/testify/mock"
)

// MockSnapshotStore is an autogenerated mock type for the SnapshotStore type
type MockSnapshotStore struct {
	mock.Mock
}

type MockSnapshotStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotStore) EXPECT() *MockSnapshotStore_Expecter {
	return &MockSnapshotStore_Expecter{mock: &_m.Mock}
}

// ListSnapshots provides a mock function with given fields: ctx, driverName, snapshotID, sourceVolumeID
func (_m *MockSnapshotStore) ListSnapshots(ctx context.Context, driverName string, snapshotID string, sourceVolumeID string) ([]store.SnapshotEntry, error) {
	ret := _m.Called(ctx, driverName, snapshotID, sourceVolumeID)

	if len(ret) == 0 {
		panic("no return value specified for ListSnapshots")
	}

	var r0 []store.SnapshotEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]store.SnapshotEntry, error)); ok {
		return rf(ctx, driverName, snapshotID, sourceVolumeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []store.SnapshotEntry); ok {
		r0 = rf(ctx, driverName, snapshotID, sourceVolumeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.SnapshotEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, driverName, snapshotID, sourceVolumeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSnapshotStore_ListSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSnapshots'
type MockSnapshotStore_ListSnapshots_Call struct {
	*mock.Call
}

// ListSnapshots is a helper method to define mock.On call
//   - ctx context.Context
//   - driverName string
//   - snapshotID string
//   - sourceVolumeID string
func (_e *MockSnapshotStore_Expecter) ListSnapshots(ctx interface{}, driverName interface{}, snapshotID interface{}, sourceVolumeID interface{}) *MockSnapshotStore_ListSnapshots_Call {
	return &MockSnapshotStore_ListSnapshots_Call{Call: _e.mock.On("ListSnapshots", ctx, driverName, snapshotID, sourceVolumeID)}
}

func (_c *MockSnapshotStore_ListSnapshots_Call) Run(run func(ctx context.Context, driverName string, snapshotID string, sourceVolumeID string)) *MockSnapshotStore_ListSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockSnapshotStore_ListSnapshots_Call) Return(_a0 []store.SnapshotEntry, _a1 error) *MockSnapshotStore_ListSnapshots_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSnapshotStore_ListSnapshots_Call) RunAndReturn(run func(context.Context, string, string, string) ([]store.SnapshotEntry, error)) *MockSnapshotStore_ListSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSnapshotStore creates a new instance of MockSnapshotStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotStore {
	mock := &MockSnapshotStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
