// Copyright 2026 ptrvsrg.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	store "github.com/ptrvsrg/csi-driver-ipfs/pkg/driver/store"
	mock "github.com/stretchr/testify/mock"
)

// MockVolumeStore is an autogenerated mock type for the VolumeStore type
type MockVolumeStore struct {
	mock.Mock
}

type MockVolumeStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeStore) EXPECT() *MockVolumeStore_Expecter {
	return &MockVolumeStore_Expecter{mock: &_m.Mock}
}

// GetVolumeAttributes provides a mock function with given fields: ctx, volumeID
func (_m *MockVolumeStore) GetVolumeAttributes(ctx context.Context, volumeID string) (*store.VolumeAttributes, error) {
	ret := _m.Called(ctx, volumeID)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeAttributes")
	}

	var r0 *store.VolumeAttributes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.VolumeAttributes, error)); ok {
		return rf(ctx, volumeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.VolumeAttributes); ok {
		r0 = rf(ctx, volumeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.VolumeAttributes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, volumeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumeStore_GetVolumeAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeAttributes'
type MockVolumeStore_GetVolumeAttributes_Call struct {
	*mock.Call
}

// GetVolumeAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - volumeID string
func (_e *MockVolumeStore_Expecter) GetVolumeAttributes(ctx interface{}, volumeID interface{}) *MockVolumeStore_GetVolumeAttributes_Call {
	return &MockVolumeStore_GetVolumeAttributes_Call{Call: _e.mock.On("GetVolumeAttributes", ctx, volumeID)}
}

func (_c *MockVolumeStore_GetVolumeAttributes_Call) Run(run func(ctx context.Context, volumeID string)) *MockVolumeStore_GetVolumeAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVolumeStore_GetVolumeAttributes_Call) Return(_a0 *store.VolumeAttributes, _a1 error) *MockVolumeStore_GetVolumeAttributes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumeStore_GetVolumeAttributes_Call) RunAndReturn(run func(context.Context, string) (*store.VolumeAttributes, error)) *MockVolumeStore_GetVolumeAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// ListVolumes provides a mock function with given fields: ctx, driverName
func (_m *MockVolumeStore) ListVolumes(ctx context.Context, driverName string) ([]*store.VolumeAttributes, error) {
	ret := _m.Called(ctx, driverName)

	if len(ret) == 0 {
		panic("no return value specified for ListVolumes")
	}

	var r0 []*store.VolumeAttributes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*store.VolumeAttributes, error)); ok {
		return rf(ctx, driverName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*store.VolumeAttributes); ok {
		r0 = rf(ctx, driverName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*store.VolumeAttributes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, driverName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVolumeStore_ListVolumes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVolumes'
type MockVolumeStore_ListVolumes_Call struct {
	*mock.Call
}

// ListVolumes is a helper method to define mock.On call
//   - ctx context.Context
//   - driverName string
func (_e *MockVolumeStore_Expecter) ListVolumes(ctx interface{}, driverName interface{}) *MockVolumeStore_ListVolumes_Call {
	return &MockVolumeStore_ListVolumes_Call{Call: _e.mock.On("ListVolumes", ctx, driverName)}
}

func (_c *MockVolumeStore_ListVolumes_Call) Run(run func(ctx context.Context, driverName string)) *MockVolumeStore_ListVolumes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockVolumeStore_ListVolumes_Call) Return(_a0 []*store.VolumeAttributes, _a1 error) *MockVolumeStore_ListVolumes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVolumeStore_ListVolumes_Call) RunAndReturn(run func(context.Context, string) ([]*store.VolumeAttributes, error)) *MockVolumeStore_ListVolumes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVolumeStore creates a new instance of MockVolumeStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeStore {
	mock := &MockVolumeStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
