apiVersion: v2
name: ipfs-cluster
description: IPFS Cluster - orchestrated pinning and replication for IPFS
type: application
version: 0.1.1
appVersion: "1.0.0"
kubeVersion: ">=1.35"
icon: https://ptrvsrg.github.io/csi-driver-ipfs/img/ipfs-logo-1024-ice-text.png
keywords:
  - ipfs
  - ipfs-cluster
  - storage
  - p2p
home: https://ipfscluster.io
sources:
  - https://github.com/ipfs/ipfs-cluster
maintainers:
  - name: ptrvsrg
    url: https://github.com/ptrvsrg
