apiVersion: v2
name: ipfs-cluster
description: IPFS Cluster - orchestrated pinning and replication for IPFS
type: application
version: 0.1.0
appVersion: "1.0.0"
kubeVersion: ">=1.35"
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ipfs-logo-1024-ice-text.png/960px-Ipfs-logo-1024-ice-text.png
keywords:
  - ipfs
  - ipfs-cluster
  - storage
  - p2p
home: https://ipfscluster.io
sources:
  - https://github.com/ipfs/ipfs-cluster
maintainers:
  - name: ptrvsrg
    url: https://github.com/ptrvsrg
