// Copyright 2026 ptrvsrg.
//
// Licensed under the Apache License, Version 2.0 (the License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an 'AS IS' BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	ipfs "github.com/ptrvsrg/csi-driver-ipfs/pkg/ipfs"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddPath provides a mock function with given fields: ctx, localPath
func (_m *MockClient) AddPath(ctx context.Context, localPath string) (string, error) {
	ret := _m.Called(ctx, localPath)

	if len(ret) == 0 {
		panic("no return value specified for AddPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, localPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, localPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, localPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_AddPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPath'
type MockClient_AddPath_Call struct {
	*mock.Call
}

// AddPath is a helper method to define mock.On call
//   - ctx context.Context
//   - localPath string
func (_e *MockClient_Expecter) AddPath(ctx interface{}, localPath interface{}) *MockClient_AddPath_Call {
	return &MockClient_AddPath_Call{Call: _e.mock.On("AddPath", ctx, localPath)}
}

func (_c *MockClient_AddPath_Call) Run(run func(ctx context.Context, localPath string)) *MockClient_AddPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_AddPath_Call) Return(_a0 string, _a1 error) *MockClient_AddPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_AddPath_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockClient_AddPath_Call {
	_c.Call.Return(run)
	return _c
}

// ExportMFS provides a mock function with given fields: ctx, mfsPath, localPath
func (_m *MockClient) ExportMFS(ctx context.Context, mfsPath string, localPath string) error {
	ret := _m.Called(ctx, mfsPath, localPath)

	if len(ret) == 0 {
		panic("no return value specified for ExportMFS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, mfsPath, localPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ExportMFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportMFS'
type MockClient_ExportMFS_Call struct {
	*mock.Call
}

// ExportMFS is a helper method to define mock.On call
//   - ctx context.Context
//   - mfsPath string
//   - localPath string
func (_e *MockClient_Expecter) ExportMFS(ctx interface{}, mfsPath interface{}, localPath interface{}) *MockClient_ExportMFS_Call {
	return &MockClient_ExportMFS_Call{Call: _e.mock.On("ExportMFS", ctx, mfsPath, localPath)}
}

func (_c *MockClient_ExportMFS_Call) Run(run func(ctx context.Context, mfsPath string, localPath string)) *MockClient_ExportMFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_ExportMFS_Call) Return(_a0 error) *MockClient_ExportMFS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ExportMFS_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_ExportMFS_Call {
	_c.Call.Return(run)
	return _c
}

// GetCIDContent provides a mock function with given fields: ctx, cidStr, destPath
func (_m *MockClient) GetCIDContent(ctx context.Context, cidStr string, destPath string) error {
	ret := _m.Called(ctx, cidStr, destPath)

	if len(ret) == 0 {
		panic("no return value specified for GetCIDContent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, cidStr, destPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_GetCIDContent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCIDContent'
type MockClient_GetCIDContent_Call struct {
	*mock.Call
}

// GetCIDContent is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
//   - destPath string
func (_e *MockClient_Expecter) GetCIDContent(ctx interface{}, cidStr interface{}, destPath interface{}) *MockClient_GetCIDContent_Call {
	return &MockClient_GetCIDContent_Call{Call: _e.mock.On("GetCIDContent", ctx, cidStr, destPath)}
}

func (_c *MockClient_GetCIDContent_Call) Run(run func(ctx context.Context, cidStr string, destPath string)) *MockClient_GetCIDContent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetCIDContent_Call) Return(_a0 error) *MockClient_GetCIDContent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_GetCIDContent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_GetCIDContent_Call {
	_c.Call.Return(run)
	return _c
}

// GetRepoStat provides a mock function with given fields: ctx
func (_m *MockClient) GetRepoStat(ctx context.Context) (*ipfs.RepoStatResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRepoStat")
	}

	var r0 *ipfs.RepoStatResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*ipfs.RepoStatResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *ipfs.RepoStatResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.RepoStatResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetRepoStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRepoStat'
type MockClient_GetRepoStat_Call struct {
	*mock.Call
}

// GetRepoStat is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetRepoStat(ctx interface{}) *MockClient_GetRepoStat_Call {
	return &MockClient_GetRepoStat_Call{Call: _e.mock.On("GetRepoStat", ctx)}
}

func (_c *MockClient_GetRepoStat_Call) Run(run func(ctx context.Context)) *MockClient_GetRepoStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_GetRepoStat_Call) Return(_a0 *ipfs.RepoStatResult, _a1 error) *MockClient_GetRepoStat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetRepoStat_Call) RunAndReturn(run func(context.Context) (*ipfs.RepoStatResult, error)) *MockClient_GetRepoStat_Call {
	_c.Call.Return(run)
	return _c
}

// ImportToMFS provides a mock function with given fields: ctx, localPath, mfsPath
func (_m *MockClient) ImportToMFS(ctx context.Context, localPath string, mfsPath string) error {
	ret := _m.Called(ctx, localPath, mfsPath)

	if len(ret) == 0 {
		panic("no return value specified for ImportToMFS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, localPath, mfsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_ImportToMFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportToMFS'
type MockClient_ImportToMFS_Call struct {
	*mock.Call
}

// ImportToMFS is a helper method to define mock.On call
//   - ctx context.Context
//   - localPath string
//   - mfsPath string
func (_e *MockClient_Expecter) ImportToMFS(ctx interface{}, localPath interface{}, mfsPath interface{}) *MockClient_ImportToMFS_Call {
	return &MockClient_ImportToMFS_Call{Call: _e.mock.On("ImportToMFS", ctx, localPath, mfsPath)}
}

func (_c *MockClient_ImportToMFS_Call) Run(run func(ctx context.Context, localPath string, mfsPath string)) *MockClient_ImportToMFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_ImportToMFS_Call) Return(_a0 error) *MockClient_ImportToMFS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_ImportToMFS_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_ImportToMFS_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirMFS provides a mock function with given fields: ctx, mfsPath
func (_m *MockClient) MkdirMFS(ctx context.Context, mfsPath string) error {
	ret := _m.Called(ctx, mfsPath)

	if len(ret) == 0 {
		panic("no return value specified for MkdirMFS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, mfsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_MkdirMFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirMFS'
type MockClient_MkdirMFS_Call struct {
	*mock.Call
}

// MkdirMFS is a helper method to define mock.On call
//   - ctx context.Context
//   - mfsPath string
func (_e *MockClient_Expecter) MkdirMFS(ctx interface{}, mfsPath interface{}) *MockClient_MkdirMFS_Call {
	return &MockClient_MkdirMFS_Call{Call: _e.mock.On("MkdirMFS", ctx, mfsPath)}
}

func (_c *MockClient_MkdirMFS_Call) Run(run func(ctx context.Context, mfsPath string)) *MockClient_MkdirMFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_MkdirMFS_Call) Return(_a0 error) *MockClient_MkdirMFS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_MkdirMFS_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_MkdirMFS_Call {
	_c.Call.Return(run)
	return _c
}

// PinCID provides a mock function with given fields: ctx, cidStr
func (_m *MockClient) PinCID(ctx context.Context, cidStr string) error {
	ret := _m.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for PinCID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cidStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_PinCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PinCID'
type MockClient_PinCID_Call struct {
	*mock.Call
}

// PinCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockClient_Expecter) PinCID(ctx interface{}, cidStr interface{}) *MockClient_PinCID_Call {
	return &MockClient_PinCID_Call{Call: _e.mock.On("PinCID", ctx, cidStr)}
}

func (_c *MockClient_PinCID_Call) Run(run func(ctx context.Context, cidStr string)) *MockClient_PinCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_PinCID_Call) Return(_a0 error) *MockClient_PinCID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_PinCID_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_PinCID_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockClient) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Ping(ctx interface{}) *MockClient_Ping_Call {
	return &MockClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockClient_Ping_Call) Run(run func(ctx context.Context)) *MockClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockClient_Ping_Call) Return(_a0 error) *MockClient_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Ping_Call) RunAndReturn(run func(context.Context) error) *MockClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// ReadCID provides a mock function with given fields: ctx, cidStr
func (_m *MockClient) ReadCID(ctx context.Context, cidStr string) (io.ReadCloser, error) {
	ret := _m.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for ReadCID")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return rf(ctx, cidStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, cidStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cidStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ReadCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadCID'
type MockClient_ReadCID_Call struct {
	*mock.Call
}

// ReadCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockClient_Expecter) ReadCID(ctx interface{}, cidStr interface{}) *MockClient_ReadCID_Call {
	return &MockClient_ReadCID_Call{Call: _e.mock.On("ReadCID", ctx, cidStr)}
}

func (_c *MockClient_ReadCID_Call) Run(run func(ctx context.Context, cidStr string)) *MockClient_ReadCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ReadCID_Call) Return(_a0 io.ReadCloser, _a1 error) *MockClient_ReadCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ReadCID_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *MockClient_ReadCID_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveMFSCID provides a mock function with given fields: ctx, mfsPath
func (_m *MockClient) ResolveMFSCID(ctx context.Context, mfsPath string) (string, error) {
	ret := _m.Called(ctx, mfsPath)

	if len(ret) == 0 {
		panic("no return value specified for ResolveMFSCID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, mfsPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, mfsPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mfsPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ResolveMFSCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveMFSCID'
type MockClient_ResolveMFSCID_Call struct {
	*mock.Call
}

// ResolveMFSCID is a helper method to define mock.On call
//   - ctx context.Context
//   - mfsPath string
func (_e *MockClient_Expecter) ResolveMFSCID(ctx interface{}, mfsPath interface{}) *MockClient_ResolveMFSCID_Call {
	return &MockClient_ResolveMFSCID_Call{Call: _e.mock.On("ResolveMFSCID", ctx, mfsPath)}
}

func (_c *MockClient_ResolveMFSCID_Call) Run(run func(ctx context.Context, mfsPath string)) *MockClient_ResolveMFSCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_ResolveMFSCID_Call) Return(_a0 string, _a1 error) *MockClient_ResolveMFSCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ResolveMFSCID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockClient_ResolveMFSCID_Call {
	_c.Call.Return(run)
	return _c
}

// RmMFS provides a mock function with given fields: ctx, mfsPath
func (_m *MockClient) RmMFS(ctx context.Context, mfsPath string) error {
	ret := _m.Called(ctx, mfsPath)

	if len(ret) == 0 {
		panic("no return value specified for RmMFS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, mfsPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_RmMFS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RmMFS'
type MockClient_RmMFS_Call struct {
	*mock.Call
}

// RmMFS is a helper method to define mock.On call
//   - ctx context.Context
//   - mfsPath string
func (_e *MockClient_Expecter) RmMFS(ctx interface{}, mfsPath interface{}) *MockClient_RmMFS_Call {
	return &MockClient_RmMFS_Call{Call: _e.mock.On("RmMFS", ctx, mfsPath)}
}

func (_c *MockClient_RmMFS_Call) Run(run func(ctx context.Context, mfsPath string)) *MockClient_RmMFS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_RmMFS_Call) Return(_a0 error) *MockClient_RmMFS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_RmMFS_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_RmMFS_Call {
	_c.Call.Return(run)
	return _c
}

// StatCID provides a mock function with given fields: ctx, cidStr
func (_m *MockClient) StatCID(ctx context.Context, cidStr string) (bool, error) {
	ret := _m.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for StatCID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, cidStr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, cidStr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cidStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_StatCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatCID'
type MockClient_StatCID_Call struct {
	*mock.Call
}

// StatCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockClient_Expecter) StatCID(ctx interface{}, cidStr interface{}) *MockClient_StatCID_Call {
	return &MockClient_StatCID_Call{Call: _e.mock.On("StatCID", ctx, cidStr)}
}

func (_c *MockClient_StatCID_Call) Run(run func(ctx context.Context, cidStr string)) *MockClient_StatCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_StatCID_Call) Return(_a0 bool, _a1 error) *MockClient_StatCID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_StatCID_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockClient_StatCID_Call {
	_c.Call.Return(run)
	return _c
}

// UnpinCID provides a mock function with given fields: ctx, cidStr
func (_m *MockClient) UnpinCID(ctx context.Context, cidStr string) error {
	ret := _m.Called(ctx, cidStr)

	if len(ret) == 0 {
		panic("no return value specified for UnpinCID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cidStr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_UnpinCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpinCID'
type MockClient_UnpinCID_Call struct {
	*mock.Call
}

// UnpinCID is a helper method to define mock.On call
//   - ctx context.Context
//   - cidStr string
func (_e *MockClient_Expecter) UnpinCID(ctx interface{}, cidStr interface{}) *MockClient_UnpinCID_Call {
	return &MockClient_UnpinCID_Call{Call: _e.mock.On("UnpinCID", ctx, cidStr)}
}

func (_c *MockClient_UnpinCID_Call) Run(run func(ctx context.Context, cidStr string)) *MockClient_UnpinCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_UnpinCID_Call) Return(_a0 error) *MockClient_UnpinCID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_UnpinCID_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_UnpinCID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
