{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipfs-cluster.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  cluster-secret: {{ required "clusterSecret is required when existingSecret is empty" .Values.clusterSecret | b64enc | quote }}
  {{- if .Values.bootstrapPeerPrivKey }}
  bootstrap-peer-priv-key: {{ .Values.bootstrapPeerPrivKey | b64enc | quote }}
  {{- end }}
{{- end }}
